---
- name: Converge
  hosts: all
  become: true

  vars:
    dkim_domains:
      - name: example.com
        selector: default
        private_key: ''  # Lets the role generate the private key.
        signing_table_pattern: '*@example.com'
    dkim_report_recipient: postmaster@example.com

  roles:
    - role: ansible-role-dkim
