---
- name: Verify role
  hosts: all
  become: yes

  tasks:
    - name: check  port 12301
      shell: ss -tp state listening sport = 12301 | grep 'opendkim'
      register: results

    - name: See service returned
      debug: var=results


