---
- name: Verify role
  hosts: all
  become: yes

  tasks:
    - name: Ensure opendkim service is enabled and running
      service:
        name: opendkim
        state: started
        enabled: yes


